workflows:
  android-workflow:
    name: Android Build
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Build APK
        script: |
          flutter pub get --no-example
          flutter build apk --debug
    artifacts:
      - build/**/outputs/**/*.apk
