workflows:
  android-workflow:
    name: Android Build
    environment:
      flutter: stable
      java: 17
    scripts:
      - name: Build APK
        script: |
          flutter pub get
          flutter build apk --debug --no-tree-shake-icons
    artifacts:
      - build/**/outputs/**/*.apk
    triggering:
      events:
        - push
